# Generated by Django 2.0.1 on 2020-02-07 05:28

import Reservation.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpId', models.IntegerField(default=Reservation.models.get_next)),
                ('bill', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fclName', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('charge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrName', models.CharField(max_length=50)),
                ('timeCharge', models.CharField(max_length=50)),
                ('halfCharge', models.CharField(max_length=50)),
                ('dayCharge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpId', models.IntegerField(default=Reservation.models.get_next)),
                ('cmpName', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.Billing')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpId', models.IntegerField(verbose_name='企業')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='開始時間')),
                ('end_time', models.TimeField(default=datetime.time(10, 0), verbose_name='終了時間')),
                ('mrName', models.CharField(max_length=50, verbose_name='会議室名')),
                ('whiteboard', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='ホワイトボード')),
                ('projector', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='プロジェクター')),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
