# Generated by Django 3.0 on 2019-12-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ImageField(upload_to='')),
                ('amount', models.IntegerField()),
                ('remain', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_facility', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('charge_fcl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_MR', models.CharField(max_length=50)),
                ('availability', models.IntegerField()),
                ('charge_MR', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=50)),
                ('company_tel', models.IntegerField()),
                ('menber_org', models.CharField(max_length=50)),
                ('menber_name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('payment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsv_number', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('name_rsvMR', models.CharField(max_length=50)),
                ('name_rsvFcl', models.CharField(max_length=50)),
                ('charge_rsv', models.IntegerField()),
            ],
        ),
    ]
