# Generated by Django 2.1.1 on 2019-12-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='fclCharge',
            new_name='charge',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='facility',
            new_name='fclName',
        ),
        migrations.RenameField(
            model_name='meetingroom',
            old_name='mrCharge',
            new_name='charge',
        ),
        migrations.RenameField(
            model_name='meetingroom',
            old_name='meetingRoom',
            new_name='mrName',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='cmpId',
        ),
    ]
